### ISSUE TITLE
Switch to using upper case identifiers (table names, column names, etc.)

### ISSUE THREAD

**Issue by timgraham** [cedar-team/django-snowflake#35]
The current implementation of [`DatabaseOperations.quote_name()`](https://github.com/cedar-team/django-snowflake/blob/37209f9ec0ce1eae9e398b247c434cbe87c4bb67/django_snowflake/operations.py#L153-L156) adds quotes around all identifiers like table and column names. This makes Snowflake treat the names case-sensitively, and Django uses lower case identifiers unless otherwise specified.

Using lower case names has some disadvantages, namely that quotes are subsequently always required around the identifires, otherwise, Snowflake will look for upper case names. One area this came up is in the raw SQL queries in Django's tests that don't include quotes. [These have been skipped](https://github.com/cedar-team/django-snowflake/blob/37209f9ec0ce1eae9e398b247c434cbe87c4bb67/django_snowflake/features.py#L228-L253) for now.

Cedar has a use case where table names are synced from PostgreSQL, apparently without quotes, so all these table names are treated as uppercase in Snowflake. To accommodate this use case and avoid the requirement of quotes in raw SQL, it might be best to adopt a similar approach as the Oracle backend, which has [`quote_name()`](https://github.com/django/django/blob/40165eecc40f9e223702a41a0cb0958515bb1f82/django/db/backends/oracle/operations.py#L341-L352) uppercase all identifiers. (This would be a breaking change for anyone who has used django-snowflake 3.2 alpha 1 to create their tables and thus has lowercased names, but since the package is at alpha stage, backward compatibility isn't critical.)

Another solution to accommodate Cedar's use case could be to add an option to make [`DatabaseWrapper.init_connection_state()`](https://github.com/cedar-team/django-snowflake/blob/37209f9ec0ce1eae9e398b247c434cbe87c4bb67/django_snowflake/base.py#L145-L151) make the query: [`ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true`](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#migrating-from-databases-that-treat-double-quoted-identifiers-as-case-insensitive).

**Comment by timgraham** [comment]
It seems that using `QUOTED_IDENTIFIERS_IGNORE_CASE` won't work because Snowflake generates constraint names that contain lower case letters, e.g. `SYS_CONSTRAINT_08edbfe1-ae43-42d6-abff-4c028a042594`.

I'm implementing the first proposal.

**Comment by chrislondon** [comment]
My current workaround is to do the following for all of my Django model fields:

```
birthday = models.DateField(db_column="BIRTHDAY")
```
